---
- hosts: all
  become: true
  tasks:
        - name: actualizando
          apt: update_cache=yes
        - name: instalando mysql
          apt: name=mysql-server state=present
        - name: instalando python mysql
          apt: name=python-mysqldb state=present
        - name: Cambiando my.cnf
          template:
           src=my.cnf.j2
           dest=/etc/mysql/my.cnf
        - name: restart mysql
          service: name=mysql state=restarted
